{
 "title": "StorJ V3 Health",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"StorJHealth\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "OS Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Reboots",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Reboots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT Limiter",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTLimit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "sda1" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Load5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Load15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Audit Crit",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Audit Warn",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedWarn" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "InfoDB check",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "InfoDBcheck" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "24hr Trending Health Diff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "PUT Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Accepted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTAcceptRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Audit Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Ratio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Repair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Repair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "24hr Count Diff - Failed/Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Deleted",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Repair Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairFail" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Repair Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "GET Ratio",
   "type": "grafana-piechart-panel",
   "description": "Downloads from this node - (uploads to client)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "DL Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "DL Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT Ratio",
   "type": "grafana-piechart-panel",
   "description": "Downloads to this node (uploads from client)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "PUT Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Concurrency Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Audit Crit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Audit Warn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedWarn" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Audit Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET Repair",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "GETRepair Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GETRepair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT Repair",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "PUTRepair Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUTRepair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "KademliaDB/DNS/Vetting check",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "VoucherCheck" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput of $host Docker0",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Storj Upload (GET)",
     "groupBy": [
      { "params": [ "12s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE \"host\" = $host AND \"path\" =~ $path AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "docker0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Storj Download (PUT)",
     "groupBy": [
      { "params": [ "12s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE \"host\" = $host AND \"path\" =~ $path AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "docker0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "targets": [
    {
     "alias": "IO WAIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "STORJ Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "€",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "STORJPriceEUR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "STORJPriceUSD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "BalanceSTORJ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "directory_size_kilobytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet val.",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$",
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "BalanceUSD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Reboot Alert",
   "type": "graph",
   "description": "Alerts if reboots >1 in $timeframe",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reboots",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Reboots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Crit",
   "type": "graph",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfoDB check",
   "type": "graph",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "InfoDBcheck" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}